import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/home.module.css";

import {db} from '../services/firebaseConnection'
import { collection, getDocs } from "firebase/firestore";

import heroImg from "../../public/assets/laptop.png"

const inter = Inter({ subsets: ["latin"] });


interface HomeProps {
  posts: number,
  comments: number,
}
export default function Home({posts, comments}: HomeProps) {
  return (
    <>
      <div className={styles.container}>

        <Head>
          <title>Tarefas+</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={styles.main}>
          <div className={styles.logoContent}>
            <Image
              className={styles.hero}
              alt="Logo tarefas"
              src={heroImg}
              priority
            />
          </div>
          <h1 className={styles.title}>Para organizar nossas tarefas</h1>

          <div className={styles.infoContent}>
            <section className={styles.box}>
              <span>{posts} posts</span>
            </section>
            <section className={styles.box}>
              <span>{comments} coments</span>
            </section>
          </div>

        </main>

      </div>

    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const commentsRef = collection(db, 'comments');
  const postsRef = collection(db, 'tarefas');

  const commentSnapShot = await getDocs(commentsRef)
  const postsSnapShot = await getDocs(postsRef)

  return {
    props: {
      posts: postsSnapShot.size || 0,
      comments: commentSnapShot.size || 0,
    },
    revalidate: 60
  }
}